refator reorder
e-davidson/angular-material-extensions pull request #86
Opened 2021-01-18 17:15 UTC by NachmanBerkowitz

2021-01-18 19:03 UTC, e-davidson requested changes

2021-01-18 19:03 UTC, e-davidson commented on projects/table-builder/src/lib/classes/table-store.ts
> +      return userDefinedOrderArr.length < viewableMetaDataArr.length
you're not taking into account 1 item added and 1 item removed.

2021-01-18 19:03 UTC, e-davidson commented on projects/table-builder/src/lib/classes/table-store.ts
> +    if( thereIsSavedOrder() && viewableMetaAddedSinceLastSave()){
in my opinion.
In a case where the developer added a column just remove the user defined array.
Like I said, there's no good way to know what the user meant.
He could mean column 2 he could mean before column 3 or after column 1.

2021-01-18 23:48 UTC, NachmanBerkowitz commented on projects/table-builder/src/lib/classes/table-store.ts
> +    mdsArr.forEach((md,index) => {
done

2021-01-18 23:48 UTC, NachmanBerkowitz commented on projects/table-builder/src/lib/classes/table-store.ts
> +    const viewableMetaDataArr = Object.values(mds).sort((a,b)=>a.order-b.order).filter(a => a.fieldType !== FieldType.Hidden);
not nogea anymore

2021-01-19 15:10 UTC, e-davidson approved these changes

2021-01-19 15:10 UTC, merged