Reusable templates
e-davidson/angular-material-extensions pull request #88
Opened 2021-01-19 21:46 UTC by e-davidson

2021-01-19 22:12 UTC, NachmanBerkowitz requested changes

2021-01-19 22:12 UTC, NachmanBerkowitz commented on projects/table-builder/src/lib/components/column-builder/column-builder.component.ts
> +    private templateService: TableService,
templateService or TableService

2021-01-19 22:12 UTC, NachmanBerkowitz commented on projects/table-builder/src/lib/pipes/transform-pipe.ts
> +import { Pipe, PipeTransform } from '@angular/core';
is this being used

2021-01-19 22:14 UTC, e-davidson commented on projects/table-builder/src/lib/pipes/transform-pipe.ts
> +import { Pipe, PipeTransform } from '@angular/core';
no, removed.

2021-01-19 22:17 UTC, e-davidson commented on projects/table-builder/src/lib/components/column-builder/column-builder.component.ts
> +    private templateService: TableService,
renamed

2021-01-20 15:59 UTC, NachmanBerkowitz approved these changes

2021-01-20 16:00 UTC, merged